### Obtener todos los productos
GET http://localhost:5000/api/productos

### Obtener producto por ID
GET http://localhost:5000/api/productos/8

### Crear producto
POST http://localhost:5000/api/productos
Content-Type: application/json

{
    "tipo": "producto",
    "nombre": "Lemon pie",
    "descripcion": "tarta de limon con merengue suizo",
    "unidad": "kg",
    "vendible": 1,
    "costo_unitario": 10.50,
    "precio_venta": 15.00
}

### crear varios productos
POST http://localhost:5000/api/productos/bulk
Content-Type: application/json

[
    {
        "tipo": "insumo",
        "nombre": "Harina 0000",
        "descripcion": "harina de trigo de alta calidad",
        "unidad": "kg",
        "vendible": 0,
        "costo_unitario": 2.00,
        "precio_venta": 0.00
    },
    {
        "tipo": "insumo",
        "nombre": "Azúcar",
        "descripcion": "azúcar blanca refinada",
        "unidad": "kg",
        "vendible": 0,
        "costo_unitario": 1.50,
        "precio_venta": 0.00
    }
]

### Actualizar producto
PUT http://localhost:5000/api/productos/19
Content-Type: application/json

{
    "tipo": "producto",
    "nombre": "Lemon pie actualizado",
    "descripcion": "tarta de limon con merengue italiano",
    "unidad": "kg",
    "vendible": 1,
    "costo_unitario": 11.00,
    "precio_venta": 16.00
}

### SECCIÓN DE RECETAS
### Obtener todas las recetas
GET http://localhost:5000/api/recetas

### Obtener receta por ID
GET http://localhost:5000/api/recetas/5

### Crear una nueva receta
POST http://localhost:5000/api/recetas
Content-Type: application/json

{
    "nombre": "lemon pie",
    "producto_id": 19
}

### Agregar ingredientes a una receta
POST http://localhost:5000/api/recetas/ingredientes 
Content-Type: application/json

{
    "receta_id": 6,
    "producto_id": 19,
    "cantidad": 0.500
}

### Actualizar una receta
PUT http://localhost:5000/api/recetas/6
Content-Type: application/json

{
    "nombre": "lemon pie actualizado",
    "producto_id": 19
}

### Eliminar una receta
DELETE http://localhost:5000/api/recetas/1


### Obtener todas las ventas
GET http://localhost:5000/api/ventas

### Obtener venta por ID
GET http://localhost:5000/api/ventas/3

### Crear una nueva venta
POST http://localhost:5000/api/ventas
Content-Type: application/json

{
    "fecha": "2024-06-15",
    "cliente_nombre": "Juan Pérez",
    "total": 45.00,
    "estado": "completado",
    "metodo_pago": "tarjeta"
}

### actualizar una venta
PUT http://localhost:5000/api/ventas/6
Content-Type: application/json

{
    "fecha": "2024-06-16",
    "cliente_nombre": "Juan Pérez",
    "total": 80.00,
    "estado": "completado",
    "metodo_pago": "efectivo"
}

### eliminar una venta 
DELETE http://localhost:5000/api/ventas/6


### creamos el usuario
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "nombre":"Camilaa",
    "email": "camizamoraa_94@hotmail.com",
    "password":"Teo4619533"
}


###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "camizamoraa_94@hotmail.com",
    "password": "Teo4619533"
}